### PR TITLE
Add setup instruction for spacemacs

### PR DESCRIPTION
**Pull request by yogsototh**
Using that `:files ("*")` in the recipe was difficult to find for me.
Hopefully this could help someone else.

### CODE REVIEW

**Comment by l3kn** [comment]
Thanks!

What problem did you run into without the `:files` part?
Maybe it could be more specific than `"*"` to only include the default files and the awk directory?

Assuming spacemacs uses / works similar to straight.el,
this would fix an issue with the straight installation method, too.

I'll set up a minimal configurations for straight / spacemacs to test this.

**Comment by yogsototh** [comment]
I've updated the list of files to `"awk"`, `"demo.org"` and `"*.el"`.

Without those files you get an error message from gawk or find during. Without the `"*.el"` it doesn't appear to discover `org-fc-hydra`.

**Comment by l3kn** [comment]
Great! I didn't think of using "awk" instead of "awk/" (which puts the files directly in the build directory).

With `:files (:defaults "awk" "demo.org")` everything gets set up correctly using straight,
can you check if `:defaults` instead of `"*.el"` works for spacemacs, too?

**Comment by yogsototh** [comment]
Yes you were right, it works as expected. 

I just stumble a potential bug with spacemacs. I needed to quit and restart emacs, for the dashboard to work correctly. I got an error related to `svg`.
After the second restart, everything work fine.

**Comment by l3kn** [comment]
Weird, can you try triggering the bug after enabling `M-x toggle-debug-on-error` and send me the full error message?

**Comment by yogsototh** [comment]
I could reproduce the error.
But I'm not sure this is caused by `org-fc`:

```
Debugger entered--Lisp error: (error "Invalid image type ‘svg’")
  signal(error ("Invalid image type ‘svg’"))
  error("Invalid image type `%s'" svg)
  image-type("<svg width=\"400\" height=\"20\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\"> <rect width=\"0.0\" height=\"20\" x=\"0\" y=\"0\" fill=\"red\"></rect> <rect width=\"200.0\" height=\"20\" x=\"0.0\" y=\"0\" fill=\"yellow\"></rect> <rect width=\"200.0\" height=\"20\" x=\"200.0\" y=\"0\" fill=\"green\"></rect> <rect width=\"0.0\" height=\"20\" x=\"400.0\" y=\"0\" fill=\"darkgreen\"></rect></svg>" svg t)
  create-image("<svg width=\"400\" height=\"20\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\"> <rect width=\"0.0\" height=\"20\" x=\"0\" y=\"0\" fill=\"red\"></rect> <rect width=\"200.0\" height=\"20\" x=\"0.0\" y=\"0\" fill=\"yellow\"></rect> <rect width=\"200.0\" height=\"20\" x=\"200.0\" y=\"0\" fill=\"green\"></rect> <rect width=\"0.0\" height=\"20\" x=\"400.0\" y=\"0\" fill=\"darkgreen\"></rect></svg>" svg t)
  apply(create-image "<svg width=\"400\" height=\"20\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\"> <rect width=\"0.0\" height=\"20\" x=\"0\" y=\"0\" fill=\"red\"></rect> <rect width=\"200.0\" height=\"20\" x=\"0.0\" y=\"0\" fill=\"yellow\"></rect> <rect width=\"200.0\" height=\"20\" x=\"200.0\" y=\"0\" fill=\"green\"></rect> <rect width=\"0.0\" height=\"20\" x=\"400.0\" y=\"0\" fill=\"darkgreen\"></rect></svg>" svg t nil)
  svg-image((svg ((width . 400) (height . 20) (version . "1.1") (xmlns . "http://www.w3.org/2000/svg")) (rect ((width . 0.0) (height . 20) (x . 0) (y . 0) (fill . "red"))) (rect ((width . 200.0) (height . 20) (x . 0.0) (y . 0) (fill . "yellow"))) (rect ((width . 200.0) (height . 20) (x . 200.0) (y . 0) (fill . "green"))) (rect ((width . 0.0) (height . 20) (x . 400.0) (y . 0) (fill . "darkgreen")))))
  (let* ((width org-fc-dashboard-bar-chart-width) (height org-fc-dashboard-bar-chart-height) (total (float (plist-get stat :total))) (pos 0) (values (list (cons (/ (plist-get stat :again) total) (quote "red")) (cons (/ (plist-get stat :hard) total) (quote "yellow")) (cons (/ (plist-get stat :good) total) (quote "green")) (cons (/ (plist-get stat :easy) total) (quote "darkgreen")))) (svg (svg-create width height))) (let ((--dolist-tail-- values)) (while --dolist-tail-- (let ((value (car --dolist-tail--))) (svg-rectangle svg pos 0 (* width (car value)) height :fill (cdr value)) (setq pos (+ pos (* width (car value)))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (svg-image svg))
  org-fc-dashboard-bar-chart((:total 2 :again 0 :hard 1 :good 1 :easy 0))
  (insert-image (org-fc-dashboard-bar-chart stat))
  (progn (insert (propertize (format "    %s (%d)\n" (cdr scope) (plist-get stat :total)) (quote face) (quote org-level-1))) (insert "    ") (insert-image (org-fc-dashboard-bar-chart stat)) (insert (org-fc-dashboard-percent-right stat)) (insert "\n\n"))
  (if (> (plist-get stat :total) 0) (progn (insert (propertize (format "    %s (%d)\n" (cdr scope) (plist-get stat :total)) (quote face) (quote org-level-1))) (insert "    ") (insert-image (org-fc-dashboard-bar-chart stat)) (insert (org-fc-dashboard-percent-right stat)) (insert "\n\n")))
  (if stat (if (> (plist-get stat :total) 0) (progn (insert (propertize (format "    %s (%d)\n" (cdr scope) (plist-get stat :total)) (quote face) (quote org-level-1))) (insert "    ") (insert-image (org-fc-dashboard-bar-chart stat)) (insert (org-fc-dashboard-percent-right stat)) (insert "\n\n"))) nil)
  (let* ((stat (and t (plist-get reviews-stats (car scope))))) (if stat (if (> (plist-get stat :total) 0) (progn (insert (propertize (format "    %s (%d)\n" (cdr scope) (plist-get stat :total)) (quote face) (quote org-level-1))) (insert "    ") (insert-image (org-fc-dashboard-bar-chart stat)) (insert (org-fc-dashboard-percent-right stat)) (insert "\n\n"))) nil))
  (let ((scope (car --dolist-tail--))) (let* ((stat (and t (plist-get reviews-stats (car scope))))) (if stat (if (> (plist-get stat :total) 0) (progn (insert (propertize (format "    %s (%d)\n" ... ...) (quote face) (quote org-level-1))) (insert "    ") (insert-image (org-fc-dashboard-bar-chart stat)) (insert (org-fc-dashboard-percent-right stat)) (insert "\n\n"))) nil)) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((scope (car --dolist-tail--))) (let* ((stat (and t (plist-get reviews-stats (car scope))))) (if stat (if (> (plist-get stat :total) 0) (progn (insert (propertize ... ... ...)) (insert "    ") (insert-image (org-fc-dashboard-bar-chart stat)) (insert (org-fc-dashboard-percent-right stat)) (insert "\n\n"))) nil)) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- (quote ((:day . "Day") (:week . "Week") (:month . "Month") (:all . "All"))))) (while --dolist-tail-- (let ((scope (car --dolist-tail--))) (let* ((stat (and t (plist-get reviews-stats ...)))) (if stat (if (> (plist-get stat :total) 0) (progn (insert ...) (insert "    ") (insert-image ...) (insert ...) (insert "\n\n"))) nil)) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  (progn (insert (propertize "  Review Statistics (All Cards)\n\n" (quote face) (quote org-level-1))) (let ((--dolist-tail-- (quote ((:day . "Day") (:week . "Week") (:month . "Month") (:all . "All"))))) (while --dolist-tail-- (let ((scope (car --dolist-tail--))) (let* ((stat (and t ...))) (if stat (if (> ... 0) (progn ... ... ... ... ...)) nil)) (setq --dolist-tail-- (cdr --dolist-tail--))))) (insert "\n"))
  (if reviews-stats (progn (insert (propertize "  Review Statistics (All Cards)\n\n" (quote face) (quote org-level-1))) (let ((--dolist-tail-- (quote ((:day . "Day") (:week . "Week") (:month . "Month") (:all . "All"))))) (while --dolist-tail-- (let ((scope (car --dolist-tail--))) (let* ((stat ...)) (if stat (if ... ...) nil)) (setq --dolist-tail-- (cdr --dolist-tail--))))) (insert "\n")))
  (save-current-buffer (set-buffer buf) (erase-buffer) (insert (propertize "Flashcards\n\n" (quote face) (quote org-level-1))) (insert (propertize "  Card Statistics\n\n" (quote face) (quote org-level-1))) (insert (format "    New: %d (day) %d (week) %d (month) \n" (plist-get stats :created-day) (plist-get stats :created-week) (plist-get stats :created-month))) (insert "\n") (insert (format "    %6d Cards, %d suspended\n" (plist-get stats :total) (plist-get stats :suspended))) (let ((--dolist-tail-- (plist-get stats :by-type))) (while --dolist-tail-- (let ((pair (car --dolist-tail--))) (insert (format "    %6d %s\n" (cdr pair) (car pair))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (insert "\n") (insert (propertize "  Position Statistics\n\n" (quote face) (quote org-level-1))) (insert (format "    %6d Due Now\n\n" (plist-get stats :due))) (let ((--dolist-tail-- (quote ((:avg-ease . "Avg. Ease") (:avg-box . "Avg. Box") (:avg-interval . "Avg. Interval (days)"))))) (while --dolist-tail-- (let ((position (car --dolist-tail--))) (insert (format "    %6.2f %s\n" (plist-get stats (car position)) (cdr position))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (insert "\n") (if reviews-stats (progn (insert (propertize "  Review Statistics (All Cards)\n\n" (quote face) (quote org-level-1))) (let ((--dolist-tail-- (quote (... ... ... ...)))) (while --dolist-tail-- (let ((scope ...)) (let* (...) (if stat ... nil)) (setq --dolist-tail-- (cdr --dolist-tail--))))) (insert "\n"))) (insert (propertize "  [r] Review\n" (quote face) (quote org-level-1))) (insert (propertize "  [q] Quit\n" (quote face) (quote org-level-1))))
  (let* ((buf (get-buffer-create org-fc-dashboard-buffer-name)) (inhibit-read-only t) (index (org-fc-index context)) (stats (org-fc-stats index)) (reviews-stats (org-fc-awk-stats-reviews))) (save-current-buffer (set-buffer buf) (erase-buffer) (insert (propertize "Flashcards\n\n" (quote face) (quote org-level-1))) (insert (propertize "  Card Statistics\n\n" (quote face) (quote org-level-1))) (insert (format "    New: %d (day) %d (week) %d (month) \n" (plist-get stats :created-day) (plist-get stats :created-week) (plist-get stats :created-month))) (insert "\n") (insert (format "    %6d Cards, %d suspended\n" (plist-get stats :total) (plist-get stats :suspended))) (let ((--dolist-tail-- (plist-get stats :by-type))) (while --dolist-tail-- (let ((pair (car --dolist-tail--))) (insert (format "    %6d %s\n" (cdr pair) (car pair))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (insert "\n") (insert (propertize "  Position Statistics\n\n" (quote face) (quote org-level-1))) (insert (format "    %6d Due Now\n\n" (plist-get stats :due))) (let ((--dolist-tail-- (quote ((:avg-ease . "Avg. Ease") (:avg-box . "Avg. Box") (:avg-interval . "Avg. Interval (days)"))))) (while --dolist-tail-- (let ((position (car --dolist-tail--))) (insert (format "    %6.2f %s\n" (plist-get stats ...) (cdr position))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (insert "\n") (if reviews-stats (progn (insert (propertize "  Review Statistics (All Cards)\n\n" (quote face) (quote org-level-1))) (let ((--dolist-tail-- (quote ...))) (while --dolist-tail-- (let (...) (let* ... ...) (setq --dolist-tail-- ...)))) (insert "\n"))) (insert (propertize "  [r] Review\n" (quote face) (quote org-level-1))) (insert (propertize "  [q] Quit\n" (quote face) (quote org-level-1)))))
  org-fc-dashboard-view((:paths all))
  org-fc-dashboard((:paths all))
  funcall-interactively(org-fc-dashboard (:paths all))
  call-interactively(org-fc-dashboard nil nil)
  command-execute(org-fc-dashboard)
```

**Comment by l3kn** [comment]
I'll add a check to see if there is svg support before including the image in the dashboard.

**Comment by l3kn** [comment]
If the display is not graphical or lacks svg support,
the dashboard now uses colored text bar chart.

A nice side-effect of this is that org-fc works in terminal emacs, too.

**Pull request merged**
