### PR TITLE
feat: Use a box of -1 to indicate the card is new

### PR DESCRIPTION
**Pull request by cashweaver**
Reference: #80

### CODE REVIEW

**Comment by l3kn** [comment]
This looks good!

Some of the additional logic could be avoided by wrapping the sm2 logic in a `let`
that sets a new box value based on `(max box 0)`.
Any thoughts on that? If you prefer a more explicit implementation,
that's fine with me too.

The review-data initialization also needs to be changed so the initial box is 0.

**Comment by cashweaver** [comment]
> The review-data initialization also needs to be changed so the initial box is 0.

Great catch! Thank you.

> Some of the additional logic could be avoided by wrapping the sm2 logic in a let
that sets a new box value based on (max box 0).

True, and I like the simplicity more than the explicit implementation. Does my change change the `let` as you expected? I wasn't quite sure what you meant by "wrapping the sm2 logic in a `let`".

**Comment by l3kn** [comment]
Nice, your change was exactly what I meant.

Give me some time to check if there are other places we need to account for the new initial box value, then this can be merged.

**Comment by cashweaver** [comment]
Checking in. Are there any changes you'd like to see before this is merged?

**Comment by cashweaver** [comment]
I borked the graph. #105 replaces this pull request.

**Pull request closed without merging**
