### PR TITLE
org-fc-awk: concatenate data when too many files with cards (fix #68)

### LINKED ISSUE #68: Some cards ignored if too many files with flash cards
I use org-fc with org-roam, and have more than 2000 files now.
Any note can contain some flash cards.

org-fc-awk-index-path function use find + xargs, and when I have too many files, xargs run awk/index.awk multiple times.

As a result, output contain multiple S-expressions.

But 'read' function from string read only first, and all other cards ignored.

It can be fixed by using 'read-from-string' function and 'append' to concatenate this lists.

### PR DESCRIPTION
**Pull request by mithraen**

### CODE REVIEW

**Comment by l3kn** [comment]
Ah, I see how this could help.

I think there's a secondary issue in the current implementation
where the number of files passed to the shell commands would exceed some OS limit
but this might only be relevant for updates (when caching is enabled), not when using awk to index all files.

Is it possible to estimate or know in advance when xargs will perform this split? 
Maybe there's some kind of chunking of the list of files on the Emacs side.

**Comment by mithraen** [comment]
It would be very fragile :(

Can you explain where is this second issue, and how I can reproduce it?

**Comment by l3kn** [comment]
I think you're right about the fragility, we can assume that find/xargs know best when to split.

The second issue might depend on the operating system and version of Emacs,
I think I ran into it after updating to Emacs 30 on linux.

It should be possible to trigger it by enabling the `org-fc-cache-mode` with lots of org files containing flashcards, or just by calling `org-fc-awk-index` with a long list of paths.

**Comment by l3kn** [comment]
We could use `(apply #'nconc (read (concat "(" output ")")))` instead, to save the calls to the identity function.

For the AWK review stats, I don't think there's a need to switch to this new parsing
because only file will be processed.

 Another benefit of this modified parsing is that `xargs` can be replaced with `parallel` to save some seconds when processing lots of files.

**Comment by mithraen** [comment]
Perhaps it would be more advantageous to omit the external braces from the AWK script. This approach would negate the need for 'nconc', 'concatenate', or similar transformations. We would only need to concatenate with braces and then read.

**Comment by mithraen** [comment]
I have implemented this concept in the updated code.

**Comment by l3kn** [comment]
Very nice, thanks!

**Pull request merged**
